name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Disable Jekyll
        run: |
          touch out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out             # Back to using 'out' directory
          branch: main           # Deploy to the main branch
          clean-exclude: |
            .git
            .github
            node_modules
            src
            package.json
            package-lock.json
            next.config.js
            postcss.config.js
            tailwind.config.js
            tsconfig.json
          token: ${{ secrets.DEPLOY_TOKEN }}